import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { ReactQueryProvider } from '@/components/providers/react-query-provider';
import './globals.css';
import { ThemeProvider } from '@/components/providers/theme-provider';
import { Updater } from '@/state/updater';

const interSans = Inter({
  variable: '--font-inter-sans',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Trading App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${interSans.variable} antialiased`}>
        <ThemeProvider attribute="class" defaultTheme="dark" disableTransitionOnChange>
          <ReactQueryProvider>
            <Updater />
            {children}
          </ReactQueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
