name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      
      - name: Install dependencies
        run: pnpm install
        working-directory: apps/trading-app

      # - name: Lint
      #   run: pnpm lint
      #   working-directory: apps/trading-app

      # - name: Type Check
      #   run: pnpm run types-check
      #   working-directory: apps/trading-app

      # - name: Unit Tests
      #   run: pnpm test
      #   working-directory: apps/trading-app

      - name: Cache Playwright Browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ hashFiles('ppnpm-lock.yaml') }}
          restore-keys: |
            playwright-${{ runner.os }}-

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps
        working-directory: apps/trading-app

      - name: Playwright Tests
        run: pnpm test:e2e
        working-directory: apps/trading-app

      - name: Upload Playwright report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: apps/trading-app/playwright-report

      - name: Upload Playwright Traces
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-traces
          path: apps/trading-app/test-results/traces

      - name: Build
        run: pnpm build
        working-directory: apps/trading-app

      - name: Start server and run Lighthouse
        run: |
          pnpm start &
          SERVER_PID=$!
          echo "Started server with PID $SERVER_PID"
          npx wait-on http://localhost:3000
          pnpm lighthouse
          kill $SERVER_PID
        working-directory: apps/trading-app
